version: '3'
services:
  top.api:
    image: docker pull ghcr.io/n-korel/api-demo/api-demo:develop
    container_name: top-api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/opt/app/.env
